version: '3'
services:
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    restart: always
    networks:
      - gateway
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbit:/data
  redis:
    container_name: redis
    hostname: redis
    image: bitnami/redis:latest
    restart: always
    networks:
      - gateway
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  #    volumes:
  #      - ./data/redis:/bitnami/redis/data
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    restart: always
    networks:
      - gateway
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  alumni-app:
    container_name: alumni-app
    hostname: alumni-app
    image: kotprotiv/alumni-app:latest
    restart: always
    networks:
      - gateway
    ports:
      - "80:80"
      - "5004:5004"
    volumes:
      - ./logs:/logs
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5004
      - DB_MONGO_HOSTNAME=mongo
      - DB_REDIS_HOSTNAME=redis
      - RABBIT_HOSTNAME=rabbit
    depends_on:
      - mongo
      - redis
      - rabbit
  alumni-file-adapter:
    container_name: alumni-file-adapter
    hostname: alumni-file-adapter
    image: kotprotiv/alumni-file-adapter:latest
    restart: always
    networks:
      - gateway
    ports:
      - "81:81"
      - "5005:5005"
    volumes:
      - ./logs:/logs
      - ./in:/in
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - RABBIT_HOSTNAME=rabbit
    depends_on:
      - rabbit
networks:
  gateway:
    driver: "bridge"