services:
  alumni-app:
    image: kotprotiv/alumni-app:latest
    restart: always
    volumes:
      - /tmp/logs:/logs
    environment:
      - DB_HOSTNAME=host.docker.internal
    ports:
      - 80:80