version: '3'
services:
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq
    restart: always
    networks:
      - gateway
    ports:
      - "6379:6379"
  #    volumes: todo: add for persistence
  redis:
    container_name: redis
    hostname: redis
    image: bitnami/redis:latest
    restart: always
    networks:
      - gateway
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami/redis/data
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    restart: always
    networks:
      - gateway
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  alumni-app:
    container_name: alumni-app
    hostname: alumni-app
    image: kotprotiv/alumni-app:latest
    restart: always
    networks:
      - gateway
    ports:
      - "80:80"
    volumes:
      - ./logs:/logs
    environment:
      - DB_MONGO_HOSTNAME=mongo
      - DB_REDIS_HOSTNAME=redis
      - RABBIT_HOSTNAME=rabbit
    depends_on:
      - mongo
      - redis
      - rabbit
  alumni-client:
    container_name: alumni-client
    hostname: alumni-client
    image: kotprotiv/alumni-client:latest
    restart: always
    networks:
      - gateway
    ports:
      - "81:81"
    volumes:
      - ./logs:/logs
    environment:
      - RABBIT_HOSTNAME=rabbit
    depends_on:
      - rabbit
networks:
  gateway:
    driver: "bridge"