server:
  port: 80
spring:
  cache:
    type: redis
  redis:
    host: ${DB_REDIS_HOSTNAME:localhost}
  data:
    mongodb:
      database: app
      port: 27017
      host: ${DB_MONGO_HOSTNAME:localhost}
logging:
  config: classpath:logback.xml
