spring:
  data:
    mongodb:
      authentication-database: app
      username: admin
      password: admin
      database: app
      port: 27017
      host: localhost
logging:
  level:
    it.kirill: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: log.log