name: CI/CD
on:
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run maven
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TOKEN: ${{ secrets.github_token }}
        run: sh release.sh
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
      - name: Upload app to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: alumni-app/target/alumni-app-${{steps.version.outputs.version}}.jar
          asset_name: alumni-app-${{steps.version.outputs.version}}.jar
          tag: ${{steps.version.outputs.version}}
      - name: Upload file adapter to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: alumni-file-adapter/target/alumni-file-adapter-${{steps.version.outputs.version}}.jar
          asset_name: alumni-file-adapter-${{steps.version.outputs.version}}.jar
          tag: ${{steps.version.outputs.version}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy app
        run: |
          ssh root@${{ secrets.SSH_HOST }} "
            cd ./deploy
            sh stop.sh
            sh start.sh
            "
